@startuml

left to right direction

actor :部门:
actor :教师:
actor :学生:

[教务管理系统] --> [登录]

[登录] --> 部门
[登录] --> 教师
[登录] --> 学生

package 部门用例集 {
    部门 --> [开课]
    [开课] --> [开设专业课]
    [开课] --> [开设公共课]
    [开课] --> [开设选修课]

    部门 --> [管理人员]
    [管理人员] --> [管理教师]
    [管理人员] --> [管理学生]
}

package 教师用例集 {
    教师 --> [教师选课]
    [教师选课] --> [选择专业课]
    [教师选课] --> [选择公共课]
    [教师选课] --> [选择选修课]

    教师 --> [查看课表]
    
    教师 --> [录入成绩]
}

package 学生用例集 {
    学生 --> [学生选课]
    [学生选课] --> [选择选修课 ]

    学生 --> [查看课表 ]

    学生 --> [查看成绩]
}



@enduml